name: publish_package
on: [workflow_dispatch]
  
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 3.0.100
            - name: Build with dotnet
              run: dotnet build --configuration Release
            - name: Pack with dotnet
              run: dotnet pack Src/SqlToSharp.csproj --output nuget-packages --configuration Release
            - name: Push with dotnet
              run: dotnet nuget push Src/nupkg/SqlToSharp.0.0.1.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        
  